### ISSUE TITLE
Add data until today and build a pipeline to add new data 

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#21] opened 2021-01-14 09:59 UTC

**Comment by ninpnin** [comment] 2021-01-14 10:28
Duplicate of #4

**Closed as completed by ninpnin** 2021-01-14 10:28 UTC

**Comment by MansMeg** [comment] 2021-01-14 10:32
Ha ha, sorry. I just add stuff now after our meeting yesterday and my use case! Good that you keep the repo clean!
